- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks: 
    - name: Copy WAR file to Tomact
      copy: 
        src: "/var/snap/jenkins/4865/webapps/ansmaven/target/mavenans.war"
        dest: "/opt/tomcat/webapps/mavenans.war"
        remote_src: no
       
    - name: Restart Tomcat
      systemd:
        name: tomcat
        state: restarted
